name: despliega a Azure

on: [push]

jobs:
  prueba:
    runs-on: ubuntu-latest
    steps:
    - name: probando
      run: echo ${{ secrets.USERNAME }}
  
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.1.4
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "index.html"
        target: "/var/www/html"